spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?user=root
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
sean:
  food: taco
frontend:
  redirect: http://localhost:3000